services:
  postgres:
    image: postgres:15
    container_name: payment-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payment_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: payment-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  k6:
    image: grafana/k6:latest
    container_name: payment-k6
    depends_on:
      - app
    volumes:
      - ./k6-scripts:/scripts
    command: run /scripts/test-script.js

volumes:
  postgres_data: